### ISSUE TITLE
Counting

### ISSUE THREAD

**Issue by dackdel** [lgraubner/sitemap-generator-cli#14]
Noob question:

Can I make it count the number of pages a site has? Example: sitemap-generator -countpage http://www.something.com

**Comment by lgraubner** [comment]
You could use `sitemap-generator --dry http://www.something.com`. At the end you get a summary like this:

```
Added 12 pages, ignored 0 pages, encountered 0 errors.
```

Counting is not the  purpose of this module so will probably not add an option for it.
