### ISSUE TITLE
Split after 50000 entries (for Google)

### ISSUE THREAD

**Issue by JLNNN** [lgraubner/sitemap-generator-cli#16]
Google allows only up to 50000 entries each sitemap. Is it possible to open another file then? :)
![google-sitemap](https://cloud.githubusercontent.com/assets/1099235/22860706/5515317a-f106-11e6-9f39-87ee2408a8e8.jpg)

Have a nice day!

**Comment by lgraubner** [comment]
Seems necessary. I will probably have to reintroduce a filepath argument as currently all output ist piped to one file.
Any wishes how to name the sitemap part files? Something like `sitemap_1.xml` etc.?

**Comment by JLNNN** [comment]
I guess that will do 👍

**Comment by buildbreakdo** [comment]
Thought it was a 10 megabyte limit not by line.. hmm..

**Comment by buildbreakdo** [comment]
Hah it's both.. how annoying:

'There are also limits on size. The sitemaps.xml file cannot exceed 10 megabytes in size, with no more than 50,000 URLs per file. But you can have multiple sitemaps in a sitemap index file, too. If you have millions of URLs, you can see where this starts to get hairy fast.'

**Comment by lgraubner** [comment]
Implemented in v6. Be aware that this is a breaking change, read more about it on the [release page](https://github.com/lgraubner/sitemap-generator-cli/releases/tag/6.0.0).
