### ISSUE TITLE
generator sitemap with cron

### ISSUE THREAD

**Issue by benoitproxi** [lgraubner/sitemap-generator-cli#17]
Hello,

I'm trying to create a sitemap with cron for my website.
It's working well when I call the command in the prompt, but when I set a cronjob, nothing happens... I'm even trying to output to a log file but it's empty...

Any clue ?
Thank you

**Comment by lgraubner** [comment]
It seems to be a problem with you cron, not with the generator. Could you paste your cron here?

**Comment by benoitproxi** [comment]
*/5 * * * * sitemap-generator https://www.website.com /var/www/html/website/web/sitemap.xml >> /tmp/sitemap.log

**Comment by lgraubner** [comment]
Try to replace sitemap-generator with the output of `which sitemap-generator`.  When the cron gets executed it might not be in your path.

**Comment by benoitproxi** [comment]
Yes, that's it :) Thanks a lot !
