### ISSUE TITLE
Angular2 Routing urls note detected

### ISSUE THREAD

**Issue by matthijssn** [lgraubner/sitemap-generator-cli#20]
Hi, 

When I run the generator on my site, the routing urls are not detected:

http://www.url.bla/#/page

In this case only http://www.url.bla will be added to the sitemap file.

**Comment by lgraubner** [comment]
Single page apps are not supported.

This module is based on a crawler which cannot crawl an spa as it expects server responses. In your case it detects every page correctly as the same as the hash does not imply a different page.
