### ISSUE TITLE
Does not close <loc> tag correctly when url ends on /

### ISSUE THREAD

**Issue by vkovalskiy** [lgraubner/sitemap-generator-cli#22]
After executing the following command: `sitemap-generator https://www.medesk.co.uk sitemap.xml`

Here is the sample output

```
<url>
    <loc>https://www.medesk.co.uk/blog/2017-06-16-digest/<loc>
  </url>
```

Notice the incorrect closing `<loc>` tag

**Comment by lgraubner** [comment]
The xml markup was incorrect. Fixed in 6.1.2, thanks for reporting!
