### ISSUE TITLE
Angular SSR sitemap generation Bug?

### ISSUE THREAD

**Issue by raza2022** [lgraubner/sitemap-generator-cli#32]
I don't think I what exactly am missing here. I am using the Complete Angular Universal SSR as given here. my site link is https://logodesignchamps.com/
I just see one link after that command `sitemap-generator https://logodesignchamps.com/ `
```
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://logodesignchamps.com/</loc>
  </url>
</urlset>
```
any help will be greatly appreciated :100:

**Comment by lgraubner** [comment]
You are not using SSR or it's not working at your side. If you open the source code of of https://logodesignchamps.com/pricing for example it does not contain HTML code for that specific page.

The crawler does not render the pages, it just checks the plain HTML code. If SSR is set up correctly it works fine.
