### ISSUE TITLE
NODE_TLS_REJECT_UNAUTHORIZED ?

### ISSUE THREAD

**Issue by victoriastuart** [lgraubner/sitemap-generator-cli#33]
```
$ sitemap-generator http://persagen.com/ /mnt/Vancouver/domains/PERSAGEN.com/2.0/sitemap.xml
(node:9038) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0'
makes TLS connections and HTTPS requests insecure by disabling certificate verification.

$ sitemap-generator -V
6.2.5
```

0 byte `sitemap.xml` generated

**Comment by victoriastuart** [comment]
$ node --version
v11.2.0

**Comment by templeman** [comment]
Same issue here.
```
$ node --version
v11.2.0
$ sitemap-generator -V
7.3.0
```
In my case I have an existing sitemap.xml file, but running the sitemap-generator command gives the `NODE_TLS_REJECT_UNAUTHORIZED` warning mentioned above and sitemap.xml contents are not updated even though the target site has new urls.

**Comment by lgraubner** [comment]
I don't think the warning has anything to do with the problems mentioned above. I was able to generate a valid sitemap.

@templeman Could you open another issue for your problem?

**Comment by templeman** [comment]
> I don't think the warning has anything to do with the problems mentioned above. I was able to generate a valid sitemap.
> 
> @templeman Could you open another issue for your problem?

Turns out my issue with the sitemap.xml not updating was user error. Feel free to delete.

**Comment by lgraubner** [comment]
@templeman Thanks for your feedback.

@victoriastuart Actually I just generated a sitemap for your site without any problems. This seems to be a different problem. Can you try with a different path? Do you have proper permissions?

The warning will be fixed in the next release.

**Comment by victoriastuart** [comment]
@lgraubner : thank you for looking into this Issue (appreciated).  The uptime on my computer  (Arch Linux) was significant, ~40d or so (enough for a couple of linux kernel updates to have transpired).  

Operating that long without rebooting eventually causes issues, so I rebooted this morning, and just now re-ran the sitemap generator.  It appeared to run fine (now), despite the `NODE_TLS...` warning, generating a 24.6KiB `sitemap.xml` file.

**tl/dr:** appears to be working fine, now.

```
$ time  sitemap-generator  http://persagen.com/  2.0/sitemap.xml                                    
(node:7828) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' 
makes TLS connections and HTTPS requests insecure by disabling certificate verification.
4:37.08

$ head -n20 sitemap.xml | grep loc
    <loc>http://persagen.com/</loc>
    <loc>http://persagen.com/about/</loc>
    <loc>http://persagen.com/contact/</loc>
    <loc>http://persagen.com/resources.html</loc>
    <loc>http://persagen.com/specialities.html</loc>
    <loc>http://persagen.com/sitemap.html</loc>

$ tail -n20 sitemap.xml | grep loc
    <loc>https://persagen.com/files/misc/Recursive_CTE-CTE.pdf</loc>
    <loc>https://persagen.com/files/misc/reading_a_postgres_EXPLAIN_ANALYZE_Query_Plan.pdf</loc>
    <loc>https://persagen.com/files/misc/Recursive_CTE-Big_O.pdf</loc>
    <loc>https://persagen.com/files/misc/Recursive_CTE-Finding_Circular_References_in_Postgres.pdf</loc>
    <loc>https://persagen.com/files/misc/Recursive_CTE-Topological_Sort.pdf</loc>
    <loc>https://persagen.com/files/misc/introduction_to_Algorithm_complexity_analysis.pdf</loc>
```

**Comment by iantearle** [comment]
Getting this now, even running trace warnings isn't doing anything. Have had this working previously.

```npx: installed 47 in 2.476s
(node:15021) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
```
Have also tried with being installed -g.
