### ISSUE TITLE
sitemap-generator outdated

### ISSUE THREAD

**Issue by chrisguttandin** [lgraubner/sitemap-generator-cli#35]
Hi @lgraubner,

first of all thanks for providing this command line tool.

I just noticed that it currently uses sitemap-generator at version 8.3.0 which still matches regular pages as AMP pages. Would it be possible to update the sitemap-generator dependency?

Many thanks in advance.

**Comment by lgraubner** [comment]
Sure. I try to make a new release today.

**Comment by lgraubner** [comment]
Sorry took a little longer. Updated and published now.

**Comment by chrisguttandin** [comment]
Thanks a lot for the update.
