### ISSUE TITLE
Option to crawl query string but not add them

### ISSUE THREAD

**Issue by duartegarin** [lgraubner/sitemap-generator-cli#38]
Hi,

At the moment we can have the option to either crawl and add query string urls or not.

The issue is that, even though we might not want to add them to the sitemap, they still should be crawled (think pagination for example).

Could we have an option to allow for this behaviour? I managed to do it by just adding a simple condition in index.js file, to check if the url is a query string before adding it to the sitemap **even though queryStrip is true**

Option could be something like "addQueryString" or something.

Thanks

**Comment by lgraubner** [comment]
I'm not sure I fully understand. You want to crawl urls with query strings but do nothing with the result?

**Comment by duartegarin** [comment]
Hi @lgraubner,

That's a very common use case. We want to crawl otherwise you won't find all content in the website, but it doesn't mean they should be added to the sitemap.

An example is a jobs portal that contains hundreds of jobs. You want to index the jobs but not all the job filter pages or paginations (that contain query string).

This PR is **exactly** what I need:

https://github.com/lgraubner/sitemap-generator/pull/61

**Comment by lgraubner** [comment]
Implemented with lgraubner/sitemap-generator#61
