### ISSUE TITLE
React/JS rendered apps not being crawled

### ISSUE THREAD

**Issue by joshiefishbein** [lgraubner/sitemap-generator-cli#39]
I just installed the CLI and ran against several JS-rendered, create-react-apps and they all resolve after the first page, assuming that it sees nothing but the root element and bails out. Trying against:

www.amplehills.com
www.coffeemanufactory.com
www.tartinebakery.com

Those URLs obviously have links but you can see that the page source will always show what it initially serves. I have no trouble with server-rendered sites.

Is there a workaround for this?

**Comment by lgraubner** [comment]
This only works for server-rendered sites.
