### ISSUE TITLE
Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0'

### ISSUE THREAD

**Issue by Jejugo** [lgraubner/sitemap-generator-cli#41]
Everytime I run `generator.on('done')` the xml file is created but it throws this  warning. I am actually deploying this app for production so this warning really scares me since the website should have a SSL certificate activated. What can I do about it?

**Comment by lgraubner** [comment]
We disable TLS checks as this module is often used in development environments which often lacks valid certificates. This doesn't say anything about the validity of an SSL certificate.

It might be nice to be able to enable/disable this with a flag.
