### ISSUE TITLE
The program gave me a sitemap.xml without any links

### ISSUE THREAD

**Issue by LimeZky** [lgraubner/sitemap-generator-cli#49]
Dear developer, I installed your program correctly, however, when I tryied to use it to create a sitemap.xml, it only gave me only one link:
![image](https://user-images.githubusercontent.com/31511420/73539892-75648c00-4469-11ea-8ccb-1f941ab237d3.png)
![image](https://user-images.githubusercontent.com/31511420/73539912-83b2a800-4469-11ea-9503-38913bac5076.png)

**Comment by luisscholl** [comment]
Same issue for me with an Angular project. If it helps, you can run the sitemap generator against it yourself: https://www.luisscholl.de/

**Comment by lgraubner** [comment]
Please see the FAQ in the main repo: https://github.com/lgraubner/sitemap-generator#faq

This section should be added in this repository too I guess.
