### ISSUE TITLE
Priority option doesn't work.

### ISSUE THREAD

**Issue by kostyaintelbit** [lgraubner/sitemap-generator-cli#55]
Running 'sitemap-generator -lpq ....' 
returns:
 <pre>
< url>
    <loc>https://www....com/login</loc>
    <lastmod>2020-03-01</lastmod>
    <priority>-q</priority>
  </url>
</pre>

**Comment by lgraubner** [comment]
I think you are using the `-p` option wrong. It expects a priority map like this:

```
sitemap-generator -lq -p "1.0,0.8,0.6,0.4" example.com
```
