### ISSUE TITLE
Too long generation time

### ISSUE THREAD

**Issue by MerkulovDev** [lgraubner/sitemap-generator-cli#58]
I have about 20k+ of products, but generating of sitemap more than about 12hours its too much, so a stopped it and get no result, because module don't saving intermediate result.

Maybe problem is circular links? On each product page i have link to "same products" and products prom this category etc. maybe module is scanning same links again and again? can it ignore links that were scanned already?

**Comment by MerkulovDev** [comment]
I think i've found a problem. Links in app are wrong. After fix will try again.

**Comment by lgraubner** [comment]
If this problem still persists please open a new issue.
