### ISSUE TITLE
Ignore “ignore”

### ISSUE THREAD

**Issue by elmimmo** [lgraubner/sitemap-generator-cli#63]
Is there a way to ignore whatever criteria is being used to ignore URLs and have those in the sitemap too?

**Comment by elmimmo** [comment]
Some URLs are ignored if their source code have a line similar to this one:

	<meta name="robots" content="noindex , nofollow" />

(which IMHO sitemap-generator-cli should ignore when run with the option `--no-respect-robots-txt`).

Comment out line 102 in /usr/local/lib/node_modules/sitemap-generator-cli/index.js in order to include those URLs in the sitemap too, like so:

```
      // /(<meta(?=[^>]+noindex).*?>)/.test(page) || // check if robots noindex is present
```

**Comment by rulatir** [comment]
The workaround no longer works - something else is at line 102 now and "noindex" does not occur anywhere in the file.

**Comment by rulatir** [comment]
There are legitimate use cases when one wants to obtain a list of HTML documents that constitute a website as seen by humans. Please add a way to absolutely override any and all logic that causes a page to be `[ IGN ]`ored.

**Comment by lgraubner** [comment]
The goal of this library is to create a sitemap for Google. `--no-respect-robots-txt` does what it says, ignore everything in `robots.txt` but not more.

If you need to crawl all of your pages you can just build something simple on your own with `simplecrawler` (which is used here under the hood as well).
