### ISSUE TITLE
ASK multi-languages

### ISSUE THREAD

**Issue by freddokresna** [lgraubner/sitemap-generator-cli#90]
i had two languages
english https://meltonice.com/index.php?lang=english and indonesia https://meltonice.com/index.php?lang=indonesian
i need to append ?lang=xxx in every request.

but i didn't find how to use this sitemap-generator for multiple languages or append get param

thanks

**Comment by lgraubner** [comment]
You can use the `--query` flag and if the other languages are linked anywhere in the source the pages will be picked up.
